/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as WhitelistRouteImport } from './routes/whitelist'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StreamersRouteImport } from './routes/streamers'
import { Route as StatusRouteImport } from './routes/status'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ScreenshotsRouteImport } from './routes/screenshots'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PatchesRouteImport } from './routes/patches'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactionsRouteImport } from './routes/factions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as AdminWhitelistRouteImport } from './routes/admin.whitelist'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStatusRouteImport } from './routes/admin.status'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRoadmapRouteImport } from './routes/admin.roadmap'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminJsonbinRouteImport } from './routes/admin.jsonbin'
import { Route as AdminFactionsRouteImport } from './routes/admin.factions'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminCronRouteImport } from './routes/admin.cron'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminBansRouteImport } from './routes/admin.bans'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitelistRoute = WhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamersRoute = StreamersRouteImport.update({
  id: '/streamers',
  path: '/streamers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsRoute = ScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchesRoute = PatchesRouteImport.update({
  id: '/patches',
  path: '/patches',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactionsRoute = FactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const AdminWhitelistRoute = AdminWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatusRoute = AdminStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJsonbinRoute = AdminJsonbinRouteImport.update({
  id: '/jsonbin',
  path: '/jsonbin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFactionsRoute = AdminFactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCronRoute = AdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBansRoute = AdminBansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/characters': typeof CharactersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/factions': typeof FactionsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forum': typeof ForumRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/lore': typeof LoreRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/patches': typeof PatchesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/rules': typeof RulesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/shop': typeof ShopRoute
  '/staff': typeof StaffRoute
  '/status': typeof StatusRoute
  '/streamers': typeof StreamersRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/vote': typeof VoteRoute
  '/whitelist': typeof WhitelistRoute
  '/wiki': typeof WikiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/bans': typeof AdminBansRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/cron': typeof AdminCronRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/factions': typeof AdminFactionsRoute
  '/admin/jsonbin': typeof AdminJsonbinRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whitelist': typeof AdminWhitelistRoute
  '/news/$id': typeof NewsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/changelog': typeof ChangelogRoute
  '/characters': typeof CharactersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/factions': typeof FactionsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forum': typeof ForumRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/lore': typeof LoreRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/patches': typeof PatchesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/rules': typeof RulesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/shop': typeof ShopRoute
  '/staff': typeof StaffRoute
  '/status': typeof StatusRoute
  '/streamers': typeof StreamersRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/vote': typeof VoteRoute
  '/whitelist': typeof WhitelistRoute
  '/wiki': typeof WikiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/bans': typeof AdminBansRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/cron': typeof AdminCronRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/factions': typeof AdminFactionsRoute
  '/admin/jsonbin': typeof AdminJsonbinRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whitelist': typeof AdminWhitelistRoute
  '/news/$id': typeof NewsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/characters': typeof CharactersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/factions': typeof FactionsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forum': typeof ForumRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/lore': typeof LoreRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/patches': typeof PatchesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/rules': typeof RulesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/shop': typeof ShopRoute
  '/staff': typeof StaffRoute
  '/status': typeof StatusRoute
  '/streamers': typeof StreamersRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/vote': typeof VoteRoute
  '/whitelist': typeof WhitelistRoute
  '/wiki': typeof WikiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/bans': typeof AdminBansRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/cron': typeof AdminCronRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/factions': typeof AdminFactionsRoute
  '/admin/jsonbin': typeof AdminJsonbinRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whitelist': typeof AdminWhitelistRoute
  '/news/$id': typeof NewsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/changelog'
    | '/characters'
    | '/contact'
    | '/dashboard'
    | '/discord'
    | '/donate'
    | '/events'
    | '/factions'
    | '/faq'
    | '/features'
    | '/forum'
    | '/gallery'
    | '/jobs'
    | '/leaderboard'
    | '/login'
    | '/lore'
    | '/map'
    | '/media'
    | '/news'
    | '/partners'
    | '/patches'
    | '/privacy'
    | '/register'
    | '/roadmap'
    | '/rules'
    | '/screenshots'
    | '/shop'
    | '/staff'
    | '/status'
    | '/streamers'
    | '/terms'
    | '/tickets'
    | '/vote'
    | '/whitelist'
    | '/wiki'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/bans'
    | '/admin/broadcast'
    | '/admin/cron'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/factions'
    | '/admin/jsonbin'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/roadmap'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/status'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/whitelist'
    | '/news/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/changelog'
    | '/characters'
    | '/contact'
    | '/dashboard'
    | '/discord'
    | '/donate'
    | '/events'
    | '/factions'
    | '/faq'
    | '/features'
    | '/forum'
    | '/gallery'
    | '/jobs'
    | '/leaderboard'
    | '/login'
    | '/lore'
    | '/map'
    | '/media'
    | '/news'
    | '/partners'
    | '/patches'
    | '/privacy'
    | '/register'
    | '/roadmap'
    | '/rules'
    | '/screenshots'
    | '/shop'
    | '/staff'
    | '/status'
    | '/streamers'
    | '/terms'
    | '/tickets'
    | '/vote'
    | '/whitelist'
    | '/wiki'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/bans'
    | '/admin/broadcast'
    | '/admin/cron'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/factions'
    | '/admin/jsonbin'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/roadmap'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/status'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/whitelist'
    | '/news/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/changelog'
    | '/characters'
    | '/contact'
    | '/dashboard'
    | '/discord'
    | '/donate'
    | '/events'
    | '/factions'
    | '/faq'
    | '/features'
    | '/forum'
    | '/gallery'
    | '/jobs'
    | '/leaderboard'
    | '/login'
    | '/lore'
    | '/map'
    | '/media'
    | '/news'
    | '/partners'
    | '/patches'
    | '/privacy'
    | '/register'
    | '/roadmap'
    | '/rules'
    | '/screenshots'
    | '/shop'
    | '/staff'
    | '/status'
    | '/streamers'
    | '/terms'
    | '/tickets'
    | '/vote'
    | '/whitelist'
    | '/wiki'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/bans'
    | '/admin/broadcast'
    | '/admin/cron'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/factions'
    | '/admin/jsonbin'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/roadmap'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/status'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/whitelist'
    | '/news/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  CharactersRoute: typeof CharactersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DiscordRoute: typeof DiscordRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FactionsRoute: typeof FactionsRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForumRoute: typeof ForumRoute
  GalleryRoute: typeof GalleryRoute
  JobsRoute: typeof JobsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  LoreRoute: typeof LoreRoute
  MapRoute: typeof MapRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PatchesRoute: typeof PatchesRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  RoadmapRoute: typeof RoadmapRoute
  RulesRoute: typeof RulesRoute
  ScreenshotsRoute: typeof ScreenshotsRoute
  ShopRoute: typeof ShopRoute
  StaffRoute: typeof StaffRoute
  StatusRoute: typeof StatusRoute
  StreamersRoute: typeof StreamersRoute
  TermsRoute: typeof TermsRoute
  TicketsRoute: typeof TicketsRoute
  VoteRoute: typeof VoteRoute
  WhitelistRoute: typeof WhitelistRoute
  WikiRoute: typeof WikiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitelist': {
      id: '/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof WhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamers': {
      id: '/streamers'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof StreamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots': {
      id: '/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof ScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patches': {
      id: '/patches'
      path: '/patches'
      fullPath: '/patches'
      preLoaderRoute: typeof PatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factions': {
      id: '/factions'
      path: '/factions'
      fullPath: '/factions'
      preLoaderRoute: typeof FactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/admin/whitelist': {
      id: '/admin/whitelist'
      path: '/whitelist'
      fullPath: '/admin/whitelist'
      preLoaderRoute: typeof AdminWhitelistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/status': {
      id: '/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AdminStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roadmap': {
      id: '/admin/roadmap'
      path: '/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jsonbin': {
      id: '/admin/jsonbin'
      path: '/jsonbin'
      fullPath: '/admin/jsonbin'
      preLoaderRoute: typeof AdminJsonbinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factions': {
      id: '/admin/factions'
      path: '/factions'
      fullPath: '/admin/factions'
      preLoaderRoute: typeof AdminFactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cron': {
      id: '/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AdminCronRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bans': {
      id: '/admin/bans'
      path: '/bans'
      fullPath: '/admin/bans'
      preLoaderRoute: typeof AdminBansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminBansRoute: typeof AdminBansRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCronRoute: typeof AdminCronRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFactionsRoute: typeof AdminFactionsRoute
  AdminJsonbinRoute: typeof AdminJsonbinRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatusRoute: typeof AdminStatusRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhitelistRoute: typeof AdminWhitelistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminBansRoute: AdminBansRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCronRoute: AdminCronRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFactionsRoute: AdminFactionsRoute,
  AdminJsonbinRoute: AdminJsonbinRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatusRoute: AdminStatusRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhitelistRoute: AdminWhitelistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  CharactersRoute: CharactersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DiscordRoute: DiscordRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FactionsRoute: FactionsRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForumRoute: ForumRoute,
  GalleryRoute: GalleryRoute,
  JobsRoute: JobsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  LoreRoute: LoreRoute,
  MapRoute: MapRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PatchesRoute: PatchesRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  RoadmapRoute: RoadmapRoute,
  RulesRoute: RulesRoute,
  ScreenshotsRoute: ScreenshotsRoute,
  ShopRoute: ShopRoute,
  StaffRoute: StaffRoute,
  StatusRoute: StatusRoute,
  StreamersRoute: StreamersRoute,
  TermsRoute: TermsRoute,
  TicketsRoute: TicketsRoute,
  VoteRoute: VoteRoute,
  WhitelistRoute: WhitelistRoute,
  WikiRoute: WikiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
